# Generated by Django 3.0.8 on 2020-07-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernm', models.CharField(max_length=32, verbose_name='用户名')),
                ('email', models.CharField(max_length=32, verbose_name='邮箱')),
                ('mphone', models.CharField(max_length=32, verbose_name='手机号')),
                ('passwd', models.CharField(max_length=32, verbose_name='密码')),
            ],
        ),
    ]
